spring:
  
  
  application:
    name: Banking
  datasource:
    url: jdbc:mysql://dbserverbanking.mysql.database.azure.com:3306/banking?createDatabaseIfNotExist=true&autoReconnect=true
    username: mohamedads@dbserverbanking
    password: Aa123456789!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    
    open-in-view: true
    database: MYSQL
    show-sql: true
    
    hibernate: 
      
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 2000